# --------------------------------------------
#           __            _
#     _____|  |   ___ ___|_|___
#    |     |  |__| . | . | |   |
#    |_|_|_|_____|___|_  |_|_|_|
#                    |___|
# made with <3 by marioogg
# version: ${project.version}
# documentation: https://mlogin.marioogg.dev
# discord: https://discord.gg/VXsGUyR5wA
# --------------------------------------------
secret-key: ""

redis: # Redis connection settings.
    host: localhost
    port: 6379
    password: ""

settings:
    # If true, will log all login attempts, commands and redis queries in console.
    debug: false
    # Checks for updates on startup. Will notify you in console if there's a new version available.
    update-check: true
    # The default language (es, en). It will load messages_es.yml or messages_en.yml
    language: en

protection:
    # Block everything before logging in (movement, chat, etc.)
    general-protection: true
    effects:
        blindness: true
        slowness: true

password:
    # The minimum length for passwords.
    min: 8
    # The maximum length for passwords.
    max: 32
