name: mLogin
version: '${project.version}'
main: me.marioogg.mlogin.spigot.SpigotPlugin
api-version: '1.20'
author: marioogg
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot