security {
    secret-key = ""
}

redis {
    host = "localhost"
    port = "6379"
    password = ""
}

sql {
    host = "localhost"
    port = 3306
    database = "mlogin"
    username = "root"
    password = ""
}